AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true

  NewCops: enable
  UseCache: true
  SuggestExtensions: false

#
# *** Layout
#
Layout/LineLength:
  Max: 120

#
# *** Metrics
#

Metrics/BlockLength:
  Max: 191
  Exclude:
    - spec/**/*

#
# *** Style
#
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

